---
- name: Configure PPPoE client on device
  community.routeros.command:
    commands:
      - /interface pppoe-client add name=pppoe-out1 interface="{{ pppoe_interface }}" user="{{ pppoe_username }}" password="{{ pppoe_password }}" add-default-route="{{ pppoe_add_default_route }}" disabled=no
