all:
  children:
    core:
      hosts:
        core-router:
    access:
      hosts:
        access-router:
    clients:
      hosts:
        client1:
        client2:
    mikrotik:
      children:
        core:
        access:
        clients:
