---
- name: Configure Core Router
  hosts: core
  gather_facts: no
  roles:
    - core

- name: Configure Access Router (PPPoE servers)
  hosts: access
  gather_facts: no
  roles:
    - access

- name: Configure PPPoE Clients
  hosts: clients
  gather_facts: no
  roles:
    - client
